### ISSUE TITLE
Multiple PGNs for environment.outside.pressure - with different values?

### ISSUE THREAD

**Issue by zubenubi** [SignalK/signalk-server-node#670]
I am noticing these 2 different PGNs coming from an airmar weatherstation:

PGN 130311 includes both temp and pressure

```
{updates: [{source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130311, src: "35"},…}],…}
context: "vessels.urn:mrn:signalk:uuid:8b725cb3-3585-4596-a450-9d0a90be118b"
updates: [{source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130311, src: "35"},…}]
0: {source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130311, src: "35"},…}
source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130311, src: "35"}
label: "canboatjs-simple"
pgn: 130311
src: "35"
type: "NMEA2000"
timestamp: "2018-11-27T12:58:23.195Z"
values: [{path: "environment.outside.temperature", value: 280.85},…]
0: {path: "environment.outside.temperature", value: 280.85}
path: "environment.outside.temperature"
value: 280.85
1: {path: "environment.outside.pressure", value: 9840000}
path: "environment.outside.pressure"
value: 9840000
```

and 130314:

```
{updates: [{source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130314, src: "35"},…}],…}
context: "vessels.urn:mrn:signalk:uuid:8b725cb3-3585-4596-a450-9d0a90be118b"
updates: [{source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130314, src: "35"},…}]
0: {source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130314, src: "35"},…}
source: {label: "canboatjs-simple", type: "NMEA2000", pgn: 130314, src: "35"}
label: "canboatjs-simple"
pgn: 130314
src: "35"
type: "NMEA2000"
timestamp: "2018-11-27T13:03:35.748Z"
values: [{path: "environment.outside.pressure", value: 98490}]
0: {path: "environment.outside.pressure", value: 98490}
path: "environment.outside.pressure"
value: 98490
```

Is anyone else seeing this? What would be a good workaround to help the display of these values?

**Comment by tkurki** [comment]
The json that you posted is not the raw sk data (something replaced with ...) and there are odd 0 and 1 values. Could you post the actual data?

What is the actual problem that you have? A single Airmar looking like two data sources, with different values? What are you using to display the data?

**Comment by zubenubi** [comment]
Im using kip and instrumentpanel for display. This json was taken from chrome developer tools under the network/ws tab. Here are some sample data from raw data logs that might be what you are looking for?
`pi@rpiNCDev:~/.signalk $ tail -f signalk-rawdata.log.2018-11-30T10 | grep 130311
1543590327473;A;2018-11-30T15:05:27.470Z,5,130311,35,255,8,79,c1,cb,6b,ff,7f,f6,03
1543590327954;A;2018-11-30T15:05:27.951Z,5,130311,35,255,8,7a,c1,cb,6b,ff,7f,f6,03
1543590328473;A;2018-11-30T15:05:28.470Z,5,130311,35,255,8,7b,c1,cb,6b,ff,7f,f6,03
1543590329012;A;2018-11-30T15:05:28.951Z,5,130311,35,255,8,7c,c1,cb,6b,ff,7f,f6,03
1543590329460;A;2018-11-30T15:05:29.459Z,5,130311,35,255,8,7d,c1,cb,6b,ff,7f,f6,03
1543590329960;A;2018-11-30T15:05:29.956Z,5,130311,35,255,8,7e,c1,cb,6b,ff,7f,f6,03
^C
pi@rpiNCDev:~/.signalk $ tail -f signalk-rawdata.log.2018-11-30T10 | grep 130314
1543590334468;A;2018-11-30T15:05:34.467Z,5,130314,35,255,8,ff,00,00,1c,7a,0f,00,ff
1543590336466;A;2018-11-30T15:05:36.465Z,5,130314,35,255,8,ff,00,00,b8,79,0f,00,ff
1543590338477;A;2018-11-30T15:05:38.475Z,5,130314,35,255,8,ff,00,00,54,79,0f,00,ff
1543590340480;A;2018-11-30T15:05:40.478Z,5,130314,35,255,8,ff,00,00,54,79,0f,00,ff
1543590342476;A;2018-11-30T15:05:42.474Z,5,130314,35,255,8,ff,00,00,54,79,0f,00,ff
^C
pi@rpiNCDev:~/.signalk $
`
The problem that I have is that the display does not seem to know how to handle the different incoming values for environment.outside.pressure ('"environment.outside.pressure" value: 9840000' and '"environment.outside.pressure" value: 98490'). If I specify mb as the display units then the values cycle between the 2 shown above and the instrumentpanel/kip gauges (understandably) don't know how to render them so it renders them both and because the 1st one has 2 extra '0's it is confusing to the end user. I don't know that the 0 and 1s represent except for an array of detected values within the PGN?

Is the airmar incorrectly emitting values for pressure or is canboat/signal misinterpreting those values or expressing them differently between the 2 pgns? I guess that is my question. As a follow-on, is there any way to ask signal feed to block or drop a specific pgn?

**Comment by tkurki** [comment]
This looks like a simple bug in n2k-signalk, see the linked PR.

PS. The trick to nice multiline code formatting is triple backticks. I fixed your samples.

**Comment by zubenubi** [comment]
By linked PR, do you mean 'fix: 130311 atmospheric pressure #136'?

I have just installed v 1.9.1 of signalk-server-node and I am still seeing the pressure reading jump between the 2 values.

I am nowhere near fluent in how github issues/pr get resolved, so I have to ask, has a fix for this been included?

**Comment by tkurki** [comment]
Yes, I meant https://github.com/SignalK/n2k-signalk/pull/136, which is waiting for review by @sbender9 .

Once resolved the change will be published in a new release of the module https://www.npmjs.com/package/@signalk/n2k-signalk. You can then upgrade this module, independent of the server version.

**Comment by zubenubi** [comment]
Thanks for the clarification.

**Comment by sbender9** [comment]
That fix has been released.
